config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    get "relationship/create"
    get "relationship/destroy"
    get "sessions/new"
    root "static_pages#home"
    get "static_pages/home"
    get "static_pages/help"
    get "static_pages/about"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :blogs, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :relationships, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  
  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true, length: {maximum: 140}
  
  default_scope -> {order(created_at: :desc)}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog

  validates :content, presence: true

  default_scope -> {order(created_at: :desc)}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
    foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
    foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  before_save :email_downcase
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}
  
  has_secure_password

  def feed
    following_ids = "SELECT followed_id FROM relationships 
      WHERE  follower_id = :user_id"
    Blog.where "user_id IN (#{following_ids}) OR user_id = :user_id",
      user_id: id
  end

  def gravatar_url options = {size: 50}
    gravatar_id = Digest::MD5.hexdigest email.downcase
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end

  def User.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create string, cost: cost
  end

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end

  private

  def email_downcase
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  include SessionsHelper

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = t ".please_login"
      redirect_to login_url
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :correct_user, only: :destroy

  def create
    @blog = current_user.blogs.build blog_params
    if @blog.save
      flash[:success] = t ".blog_created"
      redirect_to request.referrer || root_url
    else
      @feed_items = []
      render "static_pages/home"
    end
  end

  def destroy
    @blog.destroy
    flash[:danger] = t ".blog_deleted"
    redirect_to request.referrer || root_url
  end

  private

  def blog_params
    params.require(:blog).permit :title, :content
  end

  def correct_user
    @blog = current_user.blogs.find_by id: params[:id]
    redirect_to root_url if @blog.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :correct_user, only: :destroy

  def create
    @comment = current_user.comments.build comment_params
    @blogs = current_user.feed.paginate page: params[:page], per_page: 5
    if @comment.save
      respond_to do |format|
        format.html {redirect_to @comment}
        format.js
      end
    else
      @feed_items = []
      render "static_pages/home"
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html {redirect_to request.referrer || root_url}
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit :user_id, :content, :blog_id
  end

  def correct_user
    @comment = current_user.comments.find_by id: params[:id]
    redirect_to root_url if @comment.nil?
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user

  def create
    @user = User.find_by id: params[:followed_id]
    current_user.follow @user
    respond_to do |format|
      format.html {redirect_to @user}
      format.js
    end
  end

  def destroy
    @user = Relationship.find_by(id: params[:id]).followed
    current_user.unfollow @user
    respond_to do |format|
      format.html {redirect_to @user}
      format.js
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = t ".invalid_email"
      render "new"
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @feed_items = Blog.all.paginate page: params[:page], per_page: 5
    if logged_in?
      @blog  = current_user.blogs.build
      @comment = current_user.comments.build
      @feed_items = current_user.feed.paginate page: params[:page], per_page: 5
    end
  end

  def help; end

  def about; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
    :following, :followers]
    
  def show
    @user = User.find_by id: params[:id]
    @blogs = @user.blogs.paginate page: params[:page], per_page: 5
    @comment = current_user.comments.build if logged_in?
    if current_user == @user
      @blog  = current_user.blogs.build
      @feed_items = @user.feed.paginate page: params[:page], per_page: 5
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t ".welcome"
      redirect_to @user
    else
      render "new"
    end
  end

  def following
    @title = t ".following"
    @user  = User.find_by id: params[:id]
    @users = @user.following.paginate page: params[:page], per_page: 5
    render "show_follow"
  end

  def followers
    @title = t ".followers"
    @user  = User.find_by id: params[:id]
    @users = @user.followers.paginate page: params[:page], per_page: 5
    render "show_follow"
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title page_title = ""                   
    base_title = t ".title"  
    if page_title.empty?                              
      base_title                                     
    else
      page_title + " | " + base_title                 
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id] if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end
end

app/views/blogs/_blog.html.erb
<div class="row">
  <li id="blog-<%= blog.id %>">
    <%= link_to blog.user, class: "col-sm-3" do %>
      <%= image_tag blog.user.gravatar_url, class: "avata-custom2" %>
      <span><%= blog.user.name %></span>
      <span class="timestamp"><%= time_ago_in_words blog.created_at %></span>
    <% end %>
    <div class="col-sm-7" style="border: 1px solid #e8e8e8">
      <span class="title"><%= blog.title %></span>
      <span class="content"><%= blog.content %></span>
    </div>
    <div class="col-sm-2">
      <% if current_user == blog.user %>
        <%= link_to t(".delete"), blog, method: :delete,
          data: {confirm: t(".you_sure")} %>
      <% end %>
    </div>
  </li>
  
    <div id="load_comment-<%= blog.id %>" class="col-sm-8 col-sm-ofset-2 load_comment1">
      <%= render "comments/comment", blog: blog %>
    </div>
    <% if logged_in? && current_user.following?(blog.user) || (current_user == blog.user) %>
      <div id="comment_form" class="col-sm-12">
        <%= render "comments/form", blog: blog, user: blog.user %>
      </div>
    <% end %>
</div>

app/views/comments/_comment.html.erb
<% blog.comments.each do |comment| %>
  <div class="load_comment1">
    <%= link_to comment.user.name, comment.user, class: "col-sm-2" %>
    <div class="col-sm-8">
      <%= comment.content %>
      <span class="timestamp1">
        <%= time_ago_in_words comment.created_at %> 
      </span>
    </div>
    <div class="col-sm-2">
      <% if current_user == comment.user %>
        <%= link_to t("blogs.blog.delete"), comment, method: :delete,
          data: {confirm: t("blogs.blog.you_sure")}, remote: true %>
      <% end %>
    </div>
    </br>
  </div>
<% end %>

app/views/comments/_form.html.erb
  <div class="row">
    <div class="col-sm-10 pull-right">
      <%= form_for @comment, html: {id: "new_message"}, remote: true do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <div class="field col-sm-10">
          <%= f.text_field :content, placeholder: t("comments.comment.comment"),
            class: "message_content" %>
          <%= f.hidden_field :user_id, value: user.id %>
          <%= f.hidden_field :blog_id, value: blog.id %>
        </div>
        <div class="field col-sm-2">
          <%= f.submit t "comments.comment.comment" %>
        </div>
        </br>
      <% end %>
    </div>
  </div>
<script>
  $("#new_message").bind("ajax:complete", function(event,xhr,status){
    $('.message_content').val('');
  })
</script>

app/views/comments/create.js.erb
$("#load_comment-<%= @comment.blog.id %>").html("<%= j render "comments/comment",
  blog: @comment.blog %>");

app/views/comments/destroy.js.erb
$("#load_comment-<%= @comment.blog.id %>").html("<%= j render "comments/comment",
  blog: @comment.blog %>");

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", static_pages_about_path %></li>
      <li><%= link_to "Contact", "#" %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("layouts.application.title"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li>
            <%= link_to current_user do %>
              <%= image_tag current_user.gravatar_url, class: "avata-custom" %>
              <%= current_user.name %>
            <% end %>
          </li>
        <% end %>
        <li><%= link_to t(".home"), root_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t ".account" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".settings"), "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".log_in"), login_path %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t ".language" %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t(".english"), locale:"en" %></li>
            <li><%= link_to t(".vietnamese"), locale:"vi" %></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= j render "users/unfollow" %>");
$("#followers").html("<%= @user.followers.count %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render("users/follow")) %>");
$("#followers").html("<%= @user.followers.count %>");

app/views/shared/_blog_form.html.erb
<%= form_for @blog do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_field :title, placeholder: t(".title") %>
    <%= f.text_area :content, placeholder: t(".content") %>
  </div>
  <%= f.submit t(".post"), class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".form_err" %> <%= pluralize object.errors.count, "error" %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <div class="custom_a">
    <div class="flickr_pagination">
        <ol class="blogs">
          <%= render @feed_items %>
        </ol>
      <div class="page_info">
        <%= page_entries_info @feed_items %>
      </div>
      <%= will_paginate @feed_items, container: false %>
    </div>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to following_user_path @user do %>
      <strong id="following" class="stat">
        <%= @user.following.count %>
      </strong>
      <%= t "users.following.following" %>  
  <% end %>
  <%= link_to followers_user_path @user do %>
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>
      <%= t "users.followers.followers" %>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to image_tag(current_user.gravatar_url), current_user %>
<h1><%= current_user.name %></h1>
<section class="stats">
  <%= render "shared/stats" %>
</section>
<span><%= pluralize current_user.blogs.count, "blog" %></span>

app/views/static_pages/about.html.erb
<% provide :title, "About" %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/help.html.erb
<% provide :title, "Help" %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-8 col-md-offset-2">
      <section class="blog_form">
        <%= render "shared/blog_form" %>
      </section>
    </aside>
    <div class="col-md-8 col-md-offset-2">
      <h3><%= t ".news_feed" %></h3>
      <%= render "shared/feed" %>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3><%= t ".news_feed" %></h3>
      <%= render "shared/feed" %>
    </div>
  </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for current_user.active_relationships.build, remote: true do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit t(".follow"), class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following? @user %>
    <%= render "unfollow" %>
  <% else %>
    <%= render "follow" %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.active_relationships.find_by(followed_id: @user.id),
  html: {method: :delete}, remote: true do |f| %>
  <%= f.submit t(".unfollow"), class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<div class="row">
  <div class="col-sm-8 load_comment1">
    <%= link_to user do %>
      <div class="col-sm-2"> 
        <%= image_tag user.gravatar_url, class: "img-responsive img-circle" %>
      </div>
      <div class="col-sm-2"> 
        <%= user.name %>
        </div>
    <% end %>
      <%= link_to t("blogs.blog.delete"), user, method: :delete,
        data: {confirm: t("blogs.blog.you_sure")}, class: "btn btn-danger pull-right" %>
  </div>
  </br>
</div>

app/views/users/new.html.erb
<% provide :title, t(".sign_up") %>
<h1><%= t ".sign_up" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name, t(".name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email, t("sessions.new.email") %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password, t("sessions.new.password") %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, t(".password_confirmation") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t(".sign_up"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<% if current_user == @user %>
  <div class="row">
    <aside class="col-md-12">
      <section class="user_info col-sm-4">
        <%= render "shared/user_info" %>
      </section>
      <section class="blog_form col-sm-8">
        <%= render "shared/blog_form" %>
      </section>
    </aside>
    <div class="col-md-8 col-sm-offset-2 load_comment1">
      <h3><%= t "static_pages.home.news_feed" %></h3>
      <div class="custom_a">
        <div class="flickr_pagination">
          <ol class="blogs">
            <%= render @blogs %>
          </ol>
          <div class="page_info">
            <%= page_entries_info @blogs %>
          </div>
          <%= will_paginate @blogs, container: false %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <aside class="col-md-3">
      <section class="user_info">
        <h1>
          <%= image_tag @user.gravatar_url, alt: @user.name %>
          <%= @user.name %>
        </h1>
      </section>
      <section class="stats">
        <%= render "shared/stats" %>
      </section>
      <%= render "follow_form" if logged_in? %>
    </aside>
    <div class="col-md-9" id="ajax_blog">
      <% if @user.blogs.any? %>
        <h3>blogs (<%= @user.blogs.count %>)</h3>
        <div class="custom_a">
          <div class="flickr_pagination">
            <ol class="blogs">
              <%= render @blogs %>
            </ol>
            <div class="page_info">
              <%= page_entries_info @blogs %>
            </div>
            <%= will_paginate @blogs, container: false %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/show_follow.html.erb
<% provide :title, @title %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= image_tag @user.gravatar_url %>
      <h1><%= @user.name %></h1>
      <span><%= link_to t("shared.user_info.view_profile"), @user %></span>
      <span><b>Blogs:</b> <%= @user.blogs.count %></span>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to image_tag(user.gravatar_url), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <div class="custom_a">
        <div class="flickr_pagination">
          <ul class="users follow">
            <%= render @users %>
          </ul>
          <div class="page_info">
            <%= page_entries_info @users %>
          </div>
          <%= will_paginate @users, container: false %>
        </div>
      </div>
    <% end %>
  </div>
</div>